spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://stats-db:5432/stats_db
    username: stats_user
    password: stats_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    ru.practicum: INFO