server:
  port: 8080

spring:
  application:
    name: ewm-main-service

# Spring Boot Actuator конфигурация
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    ru.practicum: INFO